[tool.poetry]
name = "game-theory"
version = "0.1.0"
description = ""
authors = ["istarwyh <yihui.wang@pku.edu.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
